# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

pr:
  - master

variables:
  imageId: floor10/upscaler
#  imageTag: pr_$(System.PullRequest.PullRequestId)

steps:
- script: docker build -t $(imageId):pr_$(System.PullRequest.PullRequestId) -f docker/Dockerfile .
  displayName: 'Build of Pull request'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
